"use client";

import jsPDF from "jspdf";
import type { Recipe } from "@/lib/schemas";

const MARGIN = 20;
const PAGE_W = 190;
const PAGE_H = 277;
let y: number;

function checkPage(doc: jsPDF, needed: number) {
  if (y + needed > PAGE_H) {
    doc.addPage();
    y = MARGIN;
  }
}

function line(doc: jsPDF, h: number) {
  y += h;
}

function text(doc: jsPDF, txt: string, size: number, opts?: { bold?: boolean; color?: number[] }) {
  checkPage(doc, size + 2);
  doc.setFontSize(size);
  doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
  if (opts?.color) doc.setTextColor(opts.color[0], opts.color[1], opts.color[2]);
  else doc.setTextColor(0);
  const lines = doc.splitTextToSize(txt, PAGE_W - MARGIN * 2);
  doc.text(lines, MARGIN, y);
  y += lines.length * size * 0.352 + 2;
}

function bullet(doc: jsPDF, txt: string, size: number) {
  const maxW = PAGE_W - MARGIN * 2 - 6;
  checkPage(doc, size + 2);
  doc.setFontSize(size);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50);
  const lines = doc.splitTextToSize(txt, maxW);
  doc.text("•", MARGIN, y);
  doc.text(lines, MARGIN + 6, y);
  y += lines.length * size * 0.352 + 2;
}

function numbered(doc: jsPDF, i: number, txt: string, size: number) {
  const maxW = PAGE_W - MARGIN * 2 - 8;
  checkPage(doc, size + 2);
  doc.setFontSize(size);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50);
  const lines = doc.splitTextToSize(txt, maxW);
  doc.setTextColor(200);
  doc.text(`${i}.`, MARGIN, y);
  doc.setTextColor(50);
  doc.text(lines, MARGIN + 8, y);
  y += lines.length * size * 0.352 + 2;
}

function header(doc: jsPDF, txt: string) {
  checkPage(doc, 22);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(249, 115, 22);
  doc.text(txt.toUpperCase(), MARGIN, y);
  y += 6;
  doc.setDrawColor(249, 115, 22);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;
}

export async function downloadRecipePdf(recipe: Recipe) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  y = MARGIN;

  text(doc, recipe.title, 24, { bold: true });
  if (recipe.description) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    const desc = doc.splitTextToSize(recipe.description, PAGE_W - MARGIN * 2);
    doc.text(desc, MARGIN, y);
    y += desc.length * 3.5 + 4;
  }

  doc.setDrawColor(220);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  const stats = [
    ["Servings", String(recipe.servings)],
    ["Prep", `${recipe.prepTime} min`],
    ["Cook", `${recipe.cookTime} min`],
    ["Level", recipe.difficulty],
  ];

  const colW = (PAGE_W - MARGIN * 2) / 4;
  doc.setFontSize(13);
  stats.forEach(([label, val], i) => {
    const x = MARGIN + i * colW;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150);
    doc.text(label, x, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text(val, x, y + 5);
  });
  y += 14;

  line(doc, 6);

  header(doc, "Ingredients");
  recipe.ingredients.forEach((ing) => bullet(doc, ing, 10));
  line(doc, 4);

  header(doc, "Instructions");
  recipe.instructions.forEach((step, i) => numbered(doc, i + 1, step, 10));
  line(doc, 4);

  if (recipe.tips?.length) {
    header(doc, "Chef's Tips");
    recipe.tips.forEach((tip) => bullet(doc, tip, 10));
    line(doc, 4);
  }

  checkPage(doc, 10);
  doc.setDrawColor(200);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(180);
  doc.text("Generated by PantryPal", MARGIN, y);

  doc.save(`${recipe.title.replace(/[^a-zA-Z0-9 ]/g, "").trim()}.pdf`);
}
